/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.ibm.mobilefirst.industrial.materialsinspect.api.visit;

public class AddressElement {
	private java.lang.String address1;

 	public void setAddress1(java.lang.String address1) {
		this.address1 = address1;
	}

	public java.lang.String getAddress1() {
		return address1;
	}

	private java.lang.String state;

 	public void setState(java.lang.String state) {
		this.state = state;
	}

	public java.lang.String getState() {
		return state;
	}

	private java.lang.String address3;

 	public void setAddress3(java.lang.String address3) {
		this.address3 = address3;
	}

	public java.lang.String getAddress3() {
		return address3;
	}

	private java.lang.String address2;

 	public void setAddress2(java.lang.String address2) {
		this.address2 = address2;
	}

	public java.lang.String getAddress2() {
		return address2;
	}

	private java.lang.String city;

 	public void setCity(java.lang.String city) {
		this.city = city;
	}

	public java.lang.String getCity() {
		return city;
	}

	private java.lang.String country;

 	public void setCountry(java.lang.String country) {
		this.country = country;
	}

	public java.lang.String getCountry() {
		return country;
	}

	private java.lang.String zip;

 	public void setZip(java.lang.String zip) {
		this.zip = zip;
	}

	public java.lang.String getZip() {
		return zip;
	}

}