/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.ibm.mobilefirst.industrial.materialsinspect.api.visit;

public class StaffElement {
	private java.lang.Object ID_TYPE;

 	public void setId_type(java.lang.Object ID_TYPE) {
		this.ID_TYPE = ID_TYPE;
	}

	public java.lang.Object getId_type() {
		return ID_TYPE;
	}

	private java.lang.Object ID;

 	public void setId(java.lang.Object ID) {
		this.ID = ID;
	}

	public java.lang.Object getId() {
		return ID;
	}

	private java.lang.String EMAIL;

 	public void setEmail(java.lang.String EMAIL) {
		this.EMAIL = EMAIL;
	}

	public java.lang.String getEmail() {
		return EMAIL;
	}

	private java.lang.String POSITION;

 	public void setPosition(java.lang.String position) {
		this.POSITION = POSITION;
	}

	public java.lang.String getPosition() {
		return POSITION;
	}

	private java.lang.String TYPE;

 	public void setType(java.lang.String type) {
		this.TYPE = TYPE;
	}

	public java.lang.String getType() {
		return TYPE;
	}

	private java.lang.String PHONE;

 	public void setPhone(java.lang.String phone) {
		this.PHONE = PHONE;
	}

	public java.lang.String getPhone() {
		return PHONE;
	}

	private java.lang.String NAME;

 	public void setName(java.lang.String name) {
		this.NAME = NAME;
	}

	public java.lang.String getName() {
		return NAME;
	}

	private java.lang.String ADDRESS;

 	public void setAddress(java.lang.String ADDRESS) {
		this.ADDRESS = ADDRESS;
	}

	public java.lang.String getAddress() {
		return ADDRESS;
	}
	
	private java.lang.String PHOTO;

 	public void setPhoto(java.lang.String PHOTO) {
		this.PHOTO = PHOTO;
	}

	public java.lang.String getPhoto() {
		return PHOTO;
	}

}