/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.ibm.mobilefirst.industrial.materialsinspect.api.visit;

public class Vendor {
	private java.lang.String LOCATION_NAME;

 	public void setLocation_name(java.lang.String LOCATION_NAME) {
		this.LOCATION_NAME = LOCATION_NAME;
	}

	public java.lang.String getLocation_name() {
		return LOCATION_NAME;
	}

	private java.lang.Object ERASED;

 	public void setErased(java.lang.Object ERASED) {
		this.ERASED = ERASED;
	}

	public java.lang.Object getErased() {
		return ERASED;
	}

	private java.lang.String LOCATION_CITY;

 	public void setLocation_city(java.lang.String LOCATION_CITY) {
		this.LOCATION_CITY = LOCATION_CITY;
	}

	public java.lang.String getLocation_city() {
		return LOCATION_CITY;
	}

	private java.lang.Object WEB;

 	public void setWeb(java.lang.Object WEB) {
		this.WEB = WEB;
	}

	public java.lang.Object getWeb() {
		return WEB;
	}

	private java.lang.String LOCATION_ADDRESS;

 	public void setLocation_address(java.lang.String LOCATION_ADDRESS) {
		this.LOCATION_ADDRESS = LOCATION_ADDRESS;
	}

	public java.lang.String getLocation_address() {
		return LOCATION_ADDRESS;
	}

	private java.lang.String NAME;

 	public void setName(java.lang.String NAME) {
		this.NAME = NAME;
	}

	public java.lang.String getName() {
		return NAME;
	}

	private java.lang.String LOCATION_SPECIALITY;

 	public void setLocation_specialty(java.lang.String LOCATION_SPECIALITY) {
		this.LOCATION_SPECIALITY = LOCATION_SPECIALITY;
	}

	public java.lang.String getLocation_specialty() {
		return LOCATION_SPECIALITY;
	}

	private java.lang.Object ID_VENDOR;

 	public void setId_vendor(java.lang.Object ID_VENDOR) {
		this.ID_VENDOR = ID_VENDOR;
	}

	public java.lang.Object getId_vendor() {
		return ID_VENDOR;
	}

	private java.lang.Object BRANCHES;

 	public void setBranches(java.lang.Object BRANCHES) {
		this.BRANCHES = BRANCHES;
	}

	public java.lang.Object getBranches() {
		return BRANCHES;
	}

	private java.lang.Object PHONE;

 	public void setPhone(java.lang.Object PHONE) {
		this.PHONE = PHONE;
	}

	public java.lang.Object getPhone() {
		return PHONE;
	}

	private java.lang.Object ID_VENDOR_LOCATION;

 	public void setId_vendor_location(java.lang.Object ID_VENDOR_LOCATION) {
		this.ID_VENDOR_LOCATION = ID_VENDOR_LOCATION;
	}

	public java.lang.Object getId_vendor_location() {
		return ID_VENDOR_LOCATION;
	}

	private java.lang.String LOCATION_COUNTRY;

 	public void setLocation_country(java.lang.String LOCATION_COUNTRY) {
		this.LOCATION_COUNTRY = LOCATION_COUNTRY;
	}

	public java.lang.String getLocation_country() {
		return LOCATION_COUNTRY;
	}

	private java.lang.Object FAX;

 	public void setFax(java.lang.Object FAX) {
		this.FAX = FAX;
	}

	public java.lang.Object getFax() {
		return FAX;
	}

	private java.lang.Object TR_REF;

 	public void setTr_ref(java.lang.Object TR_REF) {
		this.TR_REF = TR_REF;
	}

	public java.lang.Object getTr_ref() {
		return TR_REF;
	}

	private java.lang.Object EMAIL;

 	public void setEmail(java.lang.Object EMAIL) {
		this.EMAIL = EMAIL;
	}

	public java.lang.Object getEmail() {
		return EMAIL;
	}

}