/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.ibm.mobilefirst.industrial.materialsinspect.api.visit;

public class VisitTeamMembersSORData {
	private Vendor VENDOR;

 	public void setVendor(Vendor VENDOR) {
		this.VENDOR = VENDOR;
	}

	public Vendor getVendor() {
		return VENDOR;
	}

	private StaffElement[] STAFF;

 	public void setStaff(StaffElement[] STAFF) {
		this.STAFF = STAFF;
	}

	public StaffElement[] getStaff() {
		return STAFF;
	}

	private CoordinatorInspectionSORData COORDINATOR_INSPECTION;

 	public void setCoordinator_inspection(CoordinatorInspectionSORData coordinator_inspection) {
		this.COORDINATOR_INSPECTION = COORDINATOR_INSPECTION;
	}

	public CoordinatorInspectionSORData getCoordinator_inspection() {
		return COORDINATOR_INSPECTION;
	}

	private ContactVendorSORData CONTACT_VENDOR;

 	public void setContact_vendor(ContactVendorSORData contact_vendor) {
		this.CONTACT_VENDOR = CONTACT_VENDOR;
	}

	public ContactVendorSORData getContact_vendor() {
		return CONTACT_VENDOR;
	}

	private CoordinatorExpeditionSORData COORDINATOR_EXPEDITION;

 	public void setCoordinator_expedition(CoordinatorExpeditionSORData coordinator_expedition) {
		this.COORDINATOR_EXPEDITION = COORDINATOR_EXPEDITION;
	}

	public CoordinatorExpeditionSORData getCoordinator_expedition() {
		return COORDINATOR_EXPEDITION;
	}

}