/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.ibm.mobilefirst.industrial.materialsinspect.api.visit;

public class VisitRequest {
	private java.lang.String visitid;

 	public void setVisitid(java.lang.String visitid) {
		this.visitid = visitid;
	}

	public java.lang.String getVisitid() {
		return visitid;
	}

	private java.lang.String date;

 	public void setDate(java.lang.String date) {
		this.date = date;
	}

	public java.lang.String getDate() {
		return date;
	}

	private java.lang.String durationunits;

 	public void setDurationunits(java.lang.String durationunits) {
		this.durationunits = durationunits;
	}

	public java.lang.String getDurationunits() {
		return durationunits;
	}

	private java.lang.String expectedduration;

 	public void setExpectedduration(java.lang.String expectedduration) {
		this.expectedduration = expectedduration;
	}

	public java.lang.String getExpectedduration() {
		return expectedduration;
	}

	private java.lang.String status;

 	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.String getStatus() {
		return status;
	}

	private java.lang.String vendorname;

 	public void setVendorname(java.lang.String vendorname) {
		this.vendorname = vendorname;
	}

	public java.lang.String getVendorname() {
		return vendorname;
	}

	private AddressElement[] address;

 	public void setAddress(AddressElement[] address) {
		this.address = address;
	}

	public AddressElement[] getAddress() {
		return address;
	}

	private java.lang.String descriptor2value;

 	public void setDescriptor2value(java.lang.String descriptor2value) {
		this.descriptor2value = descriptor2value;
	}

	public java.lang.String getDescriptor2value() {
		return descriptor2value;
	}

	private java.lang.String descriptor2label;

 	public void setDescriptor2label(java.lang.String descriptor2label) {
		this.descriptor2label = descriptor2label;
	}

	public java.lang.String getDescriptor2label() {
		return descriptor2label;
	}

	private java.lang.String manufacturername;

 	public void setManufacturername(java.lang.String manufacturername) {
		this.manufacturername = manufacturername;
	}

	public java.lang.String getManufacturername() {
		return manufacturername;
	}

	private java.lang.String displayname;

 	public void setDisplayname(java.lang.String displayname) {
		this.displayname = displayname;
	}

	public java.lang.String getDisplayname() {
		return displayname;
	}

	private java.lang.String comments;

 	public void setComments(java.lang.String comments) {
		this.comments = comments;
	}

	public java.lang.String getComments() {
		return comments;
	}

	private java.lang.String descriptor1label;

 	public void setDescriptor1label(java.lang.String descriptor1label) {
		this.descriptor1label = descriptor1label;
	}

	public java.lang.String getDescriptor1label() {
		return descriptor1label;
	}

	private java.lang.String descriptor1value;

 	public void setDescriptor1value(java.lang.String descriptor1value) {
		this.descriptor1value = descriptor1value;
	}

	public java.lang.String getDescriptor1value() {
		return descriptor1value;
	}

	private java.lang.String proposeddate;

 	public void setProposeddate(java.lang.String proposeddate) {
		this.proposeddate = proposeddate;
	}

	public java.lang.String getProposeddate() {
		return proposeddate;
	}

}