/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.ibm.mobilefirst.industrial.materialsinspect.api.user;

public class UserByUserIdSORData {
	private java.lang.Object COUNTRY;

 	public void setCountry(java.lang.Object COUNTRY) {
		this.COUNTRY = COUNTRY;
	}

	public java.lang.Object getCountry() {
		return COUNTRY;
	}

	private java.lang.Object EXPIRATION_TOKEN;

 	public void setExpiration_Token(java.lang.Object EXPIRATION_TOKEN) {
		this.EXPIRATION_TOKEN = EXPIRATION_TOKEN;
	}

	public java.lang.Object getExpiration_Token() {
		return EXPIRATION_TOKEN;
	}

	private java.lang.Object ERASED;

 	public void setErased(java.lang.Object ERASED) {
		this.ERASED = ERASED;
	}

	public java.lang.Object getErased() {
		return ERASED;
	}

	private java.lang.String NICK_NAME;

 	public void setNick_Name(java.lang.String NICK_NAME) {
		this.NICK_NAME = NICK_NAME;
	}

	public java.lang.String getNick_Name() {
		return NICK_NAME;
	}

	private java.lang.Object CREATION_DATE;

 	public void setCreation_Date(java.lang.Object CREATION_DATE) {
		this.CREATION_DATE = CREATION_DATE;
	}

	public java.lang.Object getCreation_Date() {
		return CREATION_DATE;
	}

	private java.lang.Object STATUS;

 	public void setStatus(java.lang.Object STATUS) {
		this.STATUS = STATUS;
	}

	public java.lang.Object getStatus() {
		return STATUS;
	}

	private java.lang.Object ID_NODE;

 	public void setId_Node(java.lang.Object ID_NODE) {
		this.ID_NODE = ID_NODE;
	}

	public java.lang.Object getId_Node() {
		return ID_NODE;
	}

	private java.lang.String NAME;

 	public void setName(java.lang.String NAME) {
		this.NAME = NAME;
	}

	public java.lang.String getName() {
		return NAME;
	}

	private java.lang.String SURNAME;

 	public void setSurName(java.lang.String surNAME) {
		this.SURNAME = SURNAME;
	}

	public java.lang.String getSurName() {
		return SURNAME;
	}

	private java.lang.Object MOBILE;

 	public void setMobile(java.lang.Object mobile) {
		this.MOBILE = MOBILE;
	}

	public java.lang.Object getMobile() {
		return MOBILE;
	}

	private java.lang.String EMAIL;

 	public void setEmail(java.lang.String email) {
		this.EMAIL = EMAIL;
	}

	public java.lang.String getEmail() {
		return EMAIL;
	}

	private java.lang.Object ID_USER;

 	public void setId_user(java.lang.Object ID_USER) {
		this.ID_USER = ID_USER;
	}

	public java.lang.Object getId_user() {
		return ID_USER;
	}

	private java.lang.Object PASSWORD;

 	public void setPassword(java.lang.Object password) {
		this.PASSWORD = PASSWORD;
	}

	public java.lang.Object getPassword() {
		return PASSWORD;
	}

	private java.lang.Object PASSWORD_CLEAR;

 	public void setPassword_clear(java.lang.Object password_clear) {
		this.PASSWORD_CLEAR = PASSWORD_CLEAR;
	}

	public java.lang.Object getPassword_clear() {
		return PASSWORD_CLEAR;
	}

	private java.lang.String PHONE;

 	public void setPhone(java.lang.String phone) {
		this.PHONE = PHONE;
	}

	public java.lang.String getPhone() {
		return PHONE;
	}

	private java.lang.Object TYPE;

 	public void setType(java.lang.Object type) {
		this.TYPE = TYPE;
	}

	public java.lang.Object getType() {
		return TYPE;
	}

	private java.lang.Object TR_CODE;

 	public void setTr_code(java.lang.Object TR_CODE) {
		this.TR_CODE = TR_CODE;
	}

	public java.lang.Object getTr_code() {
		return TR_CODE;
	}

	private java.lang.Object NODE_HEIGHT;

 	public void setNode_height(java.lang.Object NODE_HEIGHT) {
		this.NODE_HEIGHT = NODE_HEIGHT;
	}

	public java.lang.Object getNode_height() {
		return NODE_HEIGHT;
	}

	private java.lang.Object NODE_ACTIVE;

 	public void setNode_active(java.lang.Object node_active) {
		this.NODE_ACTIVE = NODE_ACTIVE;
	}

	public java.lang.Object getNode_active() {
		return NODE_ACTIVE;
	}

	private java.lang.Object PHOTO;

 	public void setPhoto(java.lang.Object PHOTO) {
		this.PHOTO = PHOTO;
	}

	public java.lang.Object getPhoto() {
		return PHOTO;
	}

	private java.lang.Object TOKEN;

 	public void setToken(java.lang.Object token) {
		this.TOKEN = TOKEN;
	}

	public java.lang.Object getToken() {
		return TOKEN;
	}

	private java.lang.Object USERNAME;

 	public void setUserName(java.lang.Object USERNAME) {
		this.USERNAME = USERNAME;
	}

	public java.lang.Object getUserName() {
		return USERNAME;
	}

	private java.lang.Object CITY;

 	public void setCity(java.lang.Object CITY) {
		this.CITY = CITY;
	}

	public java.lang.Object getCity() {
		return CITY;
	}

}