/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.ibm.mobilefirst.industrial.materialsinspect.api.location;

public class DataElement {
	private java.lang.String locationid;

 	public void setLocationid(java.lang.String locationid) {
		this.locationid = locationid;
	}

	public java.lang.String getLocationid() {
		return locationid;
	}

	private java.lang.String displayname;

 	public void setDisplayname(java.lang.String displayname) {
		this.displayname = displayname;
	}

	public java.lang.String getDisplayname() {
		return displayname;
	}

	private java.lang.String address;

 	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public java.lang.String getAddress() {
		return address;
	}

	private java.lang.String associatedmediafilesid;

 	public void setAssociatedmediafilesid(java.lang.String associatedmediafilesid) {
		this.associatedmediafilesid = associatedmediafilesid;
	}

	public java.lang.String getAssociatedmediafilesid() {
		return associatedmediafilesid;
	}

	private java.lang.String associateditems;

 	public void setAssociateditems(java.lang.String associateditems) {
		this.associateditems = associateditems;
	}

	public java.lang.String getAssociateditems() {
		return associateditems;
	}

}