/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.ibm.mobilefirst.industrial.materialsinspect.api.location;

public class ErrorElement {
	private java.lang.String id;

 	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getId() {
		return id;
	}

	private java.lang.String message;

 	public void setMessage(java.lang.String message) {
		this.message = message;
	}

	public java.lang.String getMessage() {
		return message;
	}

	private java.lang.String level;

 	public void setLevel(java.lang.String level) {
		this.level = level;
	}

	public java.lang.String getLevel() {
		return level;
	}

}