/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.ibm.mobilefirst.industrial.materialsinspect.api.location;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties
public class IOSLocationByLocationIdSORData {
	
	//@org.codehaus.jackson.annotate.JsonProperty("ID_LOCATION")
	private java.lang.Object ID_LOCATION;

 	public void setId_location(java.lang.Object ID_LOCATION) {
		this.ID_LOCATION = ID_LOCATION;
	}

	public java.lang.Object getId_location() {
		return ID_LOCATION;
	}
	
	//@org.codehaus.jackson.annotate.JsonProperty("NAME")
	private java.lang.String NAME;

 	public void setName(java.lang.String NAME) {
		this.NAME = NAME;
	}

	public java.lang.String getName() {
		return NAME;
	}
	
	//@org.codehaus.jackson.annotate.JsonProperty("ADDRESS")
	private java.lang.String ADDRESS;

 	public void setAddress(java.lang.String ADDRESS) {
		this.ADDRESS = ADDRESS;
	}

	public java.lang.String getAddress() {
		return ADDRESS;
	}
	
	
	private List<String> ID_ASSOCIATED_ITEMS;
	
	public List<String> getId_Associated_Items() {
		return ID_ASSOCIATED_ITEMS;
	}

	public void setId_Associated_Items(List<String> iD_ASSOCIATED_ITEMS) {
		ID_ASSOCIATED_ITEMS = iD_ASSOCIATED_ITEMS;
	}
	
	private List<String> ID_ASSOCIATED_MEDIA_FIELDS;
	
	public List<String> getId_Associated_Media_Fields() {
		return ID_ASSOCIATED_MEDIA_FIELDS;
	}

	public void setId_Associated_Media_Fields(
			List<String> iD_ASSOCIATED_MEDIA_FIELDS) {
		ID_ASSOCIATED_MEDIA_FIELDS = iD_ASSOCIATED_MEDIA_FIELDS;
	}
	
	

	

}