/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.ibm.mobilefirst.industrial.materialsinspect.api.location;

public class LocationIdDisplayData {
	private ErrorElement[] errors;

 	public void setErrors(ErrorElement[] errors) {
		this.errors = errors;
	}

	public ErrorElement[] getErrors() {
		return errors;
	}

	private DataElement[] data;

 	public void setData(DataElement[] data) {
		this.data = data;
	}

	public DataElement[] getData() {
		return data;
	}

	private Pagination pagination;

 	public void setPagination(Pagination pagination) {
		this.pagination = pagination;
	}

	public Pagination getPagination() {
		return pagination;
	}

}