/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.ibm.mobilefirst.industrial.materialsinspect.api.location;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties
public class LocationByLocationIdSORData {
	//@org.codehaus.jackson.annotate.JsonProperty("ID_STATE")
	private java.lang.Integer ID_STATE;

 	public void setId_state(java.lang.Integer ID_STATE) {
		this.ID_STATE = ID_STATE;
	}

	public java.lang.Integer getId_state() {
		return ID_STATE;
	}

	//@org.codehaus.jackson.annotate.JsonProperty("CONTACT")
	private java.lang.String CONTACT;

 	public void setContact(java.lang.String CONTACT) {
		this.CONTACT = CONTACT;
	}

	public java.lang.String getContact() {
		return CONTACT;
	}

	//@org.codehaus.jackson.annotate.JsonProperty("NAME")
	private java.lang.String NAME;

 	public void setName(java.lang.String NAME) {
		this.NAME = NAME;
	}

	public java.lang.String getName() {
		return NAME;
	}

	//@org.codehaus.jackson.annotate.JsonProperty("ADDRESS")
	private java.lang.String ADDRESS;

 	public void setAddress(java.lang.String ADDRESS) {
		this.ADDRESS = ADDRESS;
	}

	public java.lang.String getAddress() {
		return ADDRESS;
	}

	//@org.codehaus.jackson.annotate.JsonProperty("SUBVENDOR")
	private java.lang.String SUBVENDOR;

 	public void setSubvendor(java.lang.String subvendor) {
		this.SUBVENDOR = SUBVENDOR;
	}

	public java.lang.String getSubvendor() {
		return SUBVENDOR;
	}

	//@org.codehaus.jackson.annotate.JsonProperty("COUNTRY")
	private java.lang.String COUNTRY;

 	public void setCountry(java.lang.String COUNTRY) {
		this.COUNTRY = COUNTRY;
	}

	public java.lang.String getCountry() {
		return COUNTRY;
	}

	//@org.codehaus.jackson.annotate.JsonProperty("CITY")
	private java.lang.String CITY;

 	public void setCity(java.lang.String CITY) {
		this.CITY = CITY;
	}

	public java.lang.String getCity() {
		return CITY;
	}

	//@org.codehaus.jackson.annotate.JsonProperty("VENDOR")
	private java.lang.String VENDOR;

 	public void setVendor(java.lang.String VENDOR) {
		this.VENDOR = VENDOR;
	}

	public java.lang.String getVendor() {
		return VENDOR;
	}

	//@org.codehaus.jackson.annotate.JsonProperty("EXPEDITING_LEVEL")
	private java.lang.String EXPEDITING_LEVEL;

 	public void setExpediting_level(java.lang.String EXPEDITING_LEVEL) {
		this.EXPEDITING_LEVEL = EXPEDITING_LEVEL;
	}

	public java.lang.String getExpediting_level() {
		return EXPEDITING_LEVEL;
	}

	//@org.codehaus.jackson.annotate.JsonProperty("TR_REF")
	private java.lang.String TR_REF;

 	public void setTr_ref(java.lang.String TR_REF) {
		this.TR_REF = TR_REF;
	}

	public java.lang.String getTr_ref() {
		return TR_REF;
	}

	//@org.codehaus.jackson.annotate.JsonProperty("DESC")
	private java.lang.String DESC;

 	public void setDesc(java.lang.String DESC) {
		this.DESC = DESC;
	}

	public java.lang.String getDesc() {
		return DESC;
	}

	//@org.codehaus.jackson.annotate.JsonProperty("ID_SUBVENDOR")
	private java.lang.Object ID_SUBVENDOR;

 	public void setId_subvendor(java.lang.Object ID_SUBVENDOR) {
		this.ID_SUBVENDOR = ID_SUBVENDOR;
	}

	public java.lang.Object getId_subvendor() {
		return ID_SUBVENDOR;
	}

	//@org.codehaus.jackson.annotate.JsonProperty("ID_ORDER")
	private java.lang.Object ID_ORDER;

 	public void setId_order(java.lang.Object ID_ORDER) {
		this.ID_ORDER = ID_ORDER;
	}

	public java.lang.Object getId_order() {
		return ID_ORDER;
	}

	//@org.codehaus.jackson.annotate.JsonProperty("CONTACT_PHONE")
	private java.lang.String CONTACT_PHONE;

 	public void setContact_phone(java.lang.String CONTACT_PHONE) {
		this.CONTACT_PHONE = CONTACT_PHONE;
	}

	public java.lang.String getContact_phone() {
		return CONTACT_PHONE;
	}

	//@org.codehaus.jackson.annotate.JsonProperty("INSPECTION_LEVEL")
	private java.lang.String INSPECTION_LEVEL;

 	public void setInspection_level(java.lang.String INSPECTION_LEVEL) {
		this.INSPECTION_LEVEL = INSPECTION_LEVEL;
	}

	public java.lang.String getInspection_level() {
		return INSPECTION_LEVEL;
	}

	//@org.codehaus.jackson.annotate.JsonProperty("STATE")
	private java.lang.String STATE;

 	public void setState(java.lang.String STATE) {
		this.STATE = STATE;
	}

	public java.lang.String getState() {
		return STATE;
	}

	//@org.codehaus.jackson.annotate.JsonProperty("ID_TEMPLATE")
	private java.lang.Object ID_TEMPLATE;

 	public void setId_template(java.lang.Object ID_TEMPLATE) {
		this.ID_TEMPLATE = ID_TEMPLATE;
	}

	public java.lang.Object getId_template() {
		return ID_TEMPLATE;
	}

	//@org.codehaus.jackson.annotate.JsonProperty("CONTACT_NAME")
	private java.lang.String CONTACT_NAME;

 	public void setContact_name(java.lang.String CONTACT_NAME) {
		this.CONTACT_NAME = CONTACT_NAME;
	}

	public java.lang.String getContact_name() {
		return CONTACT_NAME;
	}

	//@org.codehaus.jackson.annotate.JsonProperty("VENDOR_ADDRESS")
	private java.lang.String VENDOR_ADDRESS;

 	public void setVendor_address(java.lang.String VENDOR_ADDRESS) {
		this.VENDOR_ADDRESS = VENDOR_ADDRESS;
	}

	public java.lang.String getVendor_address() {
		return VENDOR_ADDRESS;
	}

	//@org.codehaus.jackson.annotate.JsonProperty("ID_VENDOR")
	private java.lang.Object ID_VENDOR;

 	public void setId_vendor(java.lang.Object ID_VENDOR) {
		this.ID_VENDOR = ID_VENDOR;
	}

	public java.lang.Object getId_vendor() {
		return ID_VENDOR;
	}

	//@org.codehaus.jackson.annotate.JsonProperty("ID_LOCATION")
	private java.lang.Object ID_LOCATION;

 	public void setId_location(java.lang.Object ID_LOCATION) {
		this.ID_LOCATION = ID_LOCATION;
	}

	public java.lang.Object getId_location() {
		return ID_LOCATION;
	}

	//@org.codehaus.jackson.annotate.JsonProperty("CONTACT_FAX")
	private java.lang.String CONTACT_FAX;

 	public void setContact_fax(java.lang.String CONTACT_FAX) {
		this.CONTACT_FAX = CONTACT_FAX;
	}

	public java.lang.String getContact_fax() {
		return CONTACT_FAX;
	}

	//@org.codehaus.jackson.annotate.JsonProperty("CODE")
	private java.lang.String CODE;

 	public void setCode(java.lang.String CODE) {
		this.CODE = CODE;
	}

	public java.lang.String getCode() {
		return CODE;
	}

	//@org.codehaus.jackson.annotate.JsonProperty("CONTACT_EMAIL")
	private java.lang.String CONTACT_EMAIL;

 	public void setContact_email(java.lang.String CONTACT_EMAIL) {
		this.CONTACT_EMAIL = CONTACT_EMAIL;
	}

	public java.lang.String getContact_email() {
		return CONTACT_EMAIL;
	}

	//@org.codehaus.jackson.annotate.JsonProperty("ORDER_DESCRIPTION")
	private java.lang.String ORDER_DESCRIPTION;

 	public void setOrder_description(java.lang.String ORDER_DESCRIPTION) {
		this.ORDER_DESCRIPTION = ORDER_DESCRIPTION;
	}

	public java.lang.String getOrder_description() {
		return ORDER_DESCRIPTION;
	}

	//@org.codehaus.jackson.annotate.JsonProperty("TEMPLATE_NAME")
	private java.lang.String TEMPLATE_NAME;

 	public void setTemplate_name(java.lang.String TEMPLATE_NAME) {
		this.TEMPLATE_NAME = TEMPLATE_NAME;
	}

	public java.lang.String getTemplate_name() {
		return TEMPLATE_NAME;
	}

}