/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.ibm.mobilefirst.industrial.materialsinspect.api.location;

public class Pagination {
	private java.lang.Integer offset;

 	public void setOffset(java.lang.Integer offset) {
		this.offset = offset;
	}

	public java.lang.Integer getOffset() {
		return offset;
	}

	private java.lang.Integer size;

 	public void setSize(java.lang.Integer size) {
		this.size = size;
	}

	public java.lang.Integer getSize() {
		return size;
	}

}