/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.ibm.mobilefirst.industrial.materialsinspect.api.user.Location;

public class DocumentVendorByLocationIdSORData {
	private java.lang.String ORDER;

 	public void setOrder(java.lang.String ORDER) {
		this.ORDER = ORDER;
	}

	public java.lang.String getOrder() {
		return ORDER;
	}

	private java.lang.String PROJECT;

 	public void setProject(java.lang.String PROJECT) {
		this.PROJECT = PROJECT;
	}

	public java.lang.String getProject() {
		return PROJECT;
	}

	private java.lang.Object ID_DOCUMENT;

 	public void setId_document(java.lang.Object ID_DOCUMENT) {
		this.ID_DOCUMENT = ID_DOCUMENT;
	}

	public java.lang.Object getId_document() {
		return ID_DOCUMENT;
	}

	private java.lang.Object DATE_MOD;

 	public void setDate_mod(java.lang.Object DATE_MOD) {
		this.DATE_MOD = DATE_MOD;
	}

	public java.lang.Object getDate_mod() {
		return DATE_MOD;
	}

	private java.lang.String DATE_NEW;

 	public void setDate_new(java.lang.String DATE_NEW) {
		this.DATE_NEW = DATE_NEW;
	}

	public java.lang.String getDate_new() {
		return DATE_NEW;
	}

	private java.lang.String STATUS;

 	public void setStatus(java.lang.String status) {
		this.STATUS = STATUS;
	}

	public java.lang.String getStatus() {
		return STATUS;
	}

	private java.lang.String DATE_RECEIVED;

 	public void setDate_received(java.lang.String DATE_RECEIVED) {
		this.DATE_RECEIVED = DATE_RECEIVED;
	}

	public java.lang.String getDate_received() {
		return DATE_RECEIVED;
	}

	private java.lang.String TITLE;

 	public void setTitle(java.lang.String TITLE) {
		this.TITLE = TITLE;
	}

	public java.lang.String getTitle() {
		return TITLE;
	}

	private java.lang.String FILEPATH;

 	public void setFilepath(java.lang.String filepath) {
		this.FILEPATH = FILEPATH;
	}

	public java.lang.String getFilepath() {
		return FILEPATH;
	}

	private java.lang.String ID_ITEM;

 	public void setId_item(java.lang.String ID_ITEM) {
		this.ID_ITEM = ID_ITEM;
	}

	public java.lang.String getId_item() {
		return ID_ITEM;
	}

	private java.lang.String NAME;

 	public void setName(java.lang.String NAME) {
		this.NAME = NAME;
	}

	public java.lang.String getName() {
		return NAME;
	}

	private java.lang.String REV_TR;

 	public void setRev_tr(java.lang.String REV_TR) {
		this.REV_TR = REV_TR;
	}

	public java.lang.String getRev_tr() {
		return REV_TR;
	}

	private java.lang.String TR_STATUS;

 	public void setTr_status(java.lang.String TR_STATUS) {
		this.TR_STATUS = TR_STATUS;
	}

	public java.lang.String getTr_status() {
		return TR_STATUS;
	}

}