/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.ibm.mobilefirst.industrial.materialsinspect.api.user.Location;

public class LocationItemsByOrderIdAndLocationIdSORData {
	private java.lang.String POS;

 	public void setPos(java.lang.String POS) {
		this.POS = POS;
	}

	public java.lang.String getPos() {
		return POS;
	}

	private java.lang.Integer ID_EXPEDITION_LEVEL;

 	public void setId_expedition_level(java.lang.Integer ID_EXPEDITION_LEVEL) {
		this.ID_EXPEDITION_LEVEL = ID_EXPEDITION_LEVEL;
	}

	public java.lang.Integer getId_expedition_level() {
		return ID_EXPEDITION_LEVEL;
	}

	private java.lang.Integer ID_ITEM;

 	public void setId_item(java.lang.Integer ID_ITEM) {
		this.ID_ITEM = ID_ITEM;
	}

	public java.lang.Integer getId_item() {
		return ID_ITEM;
	}

	private java.lang.Double QUANTITY;

 	public void setQuantity(java.lang.Double QUANTITY) {
		this.QUANTITY = QUANTITY;
	}

	public java.lang.Double getQuantity() {
		return QUANTITY;
	}

	private java.lang.String UNIT;

 	public void setUnit(java.lang.String UNIT) {
		this.UNIT = UNIT;
	}

	public java.lang.String getUnit() {
		return UNIT;
	}

	private java.lang.String TAG_DESC;

 	public void setTag_desc(java.lang.String TAG_DESC) {
		this.TAG_DESC = TAG_DESC;
	}

	public java.lang.String getTag_desc() {
		return TAG_DESC;
	}

	private java.lang.Integer ID_INSPECTION_LEVEL_PREV;

 	public void setId_inspection_level_prev(java.lang.Integer ID_INSPECTION_LEVEL_PREV) {
		this.ID_INSPECTION_LEVEL_PREV = ID_INSPECTION_LEVEL_PREV;
	}

	public java.lang.Integer getId_inspection_level_prev() {
		return ID_INSPECTION_LEVEL_PREV;
	}

	private java.lang.String SHIP_POS_SUB;

 	public void setShip_pos_sub(java.lang.String SHIP_POS_SUB) {
		this.SHIP_POS_SUB = SHIP_POS_SUB;
	}

	public java.lang.String getShip_pos_sub() {
		return SHIP_POS_SUB;
	}

	private java.lang.Integer ID_FAMILY;

 	public void setId_family(java.lang.Integer ID_FAMILY) {
		this.ID_FAMILY = ID_FAMILY;
	}

	public java.lang.Integer getId_family() {
		return ID_FAMILY;
	}

	private java.lang.String EXPEDITION_LEVEL;

 	public void setExpedition_level(java.lang.String EXPEDITION_LEVEL) {
		this.EXPEDITION_LEVEL = EXPEDITION_LEVEL;
	}

	public java.lang.String getExpedition_level() {
		return EXPEDITION_LEVEL;
	}

	private java.lang.String SUPPL;

 	public void setSuppl(java.lang.String SUPPL) {
		this.SUPPL = SUPPL;
	}

	public java.lang.String getSuppl() {
		return SUPPL;
	}

	private java.lang.String INCOTERM;

 	public void setIncoterm(java.lang.String INCOTERM) {
		this.INCOTERM = INCOTERM;
	}

	public java.lang.String getIncoterm() {
		return INCOTERM;
	}

	private java.lang.String IRC_DESC;

 	public void setIrc_desc(java.lang.String IRC_DESC) {
		this.IRC_DESC = IRC_DESC;
	}

	public java.lang.String getIrc_desc() {
		return IRC_DESC;
	}

	private java.lang.String INSP_FLAG;

 	public void setInsp_flag(java.lang.String INSP_FLAG) {
		this.INSP_FLAG = INSP_FLAG;
	}

	public java.lang.String getInsp_flag() {
		return INSP_FLAG;
	}

	private java.lang.String FAMILY;

 	public void setFamily(java.lang.String family) {
		this.FAMILY = FAMILY;
	}

	public java.lang.String getFamily() {
		return FAMILY;
	}

	private java.lang.String IDENT;

 	public void setIdent(java.lang.String ident) {
		this.IDENT = IDENT;
	}

	public java.lang.String getIdent() {
		return IDENT;
	}

	private java.lang.String CC;

 	public void setCc(java.lang.String CC) {
		this.CC = CC;
	}

	public java.lang.String getCc() {
		return CC;
	}

	private java.lang.Double PENDING_QUANTITY;

 	public void setPending_quantity(java.lang.Double PENDING_QUANTITY) {
		this.PENDING_QUANTITY = PENDING_QUANTITY;
	}

	public java.lang.Double getPending_quantity() {
		return PENDING_QUANTITY;
	}

	private java.lang.String SHIP_POS;

 	public void setShip_pos(java.lang.String SHIP_POS) {
		this.SHIP_POS = SHIP_POS;
	}

	public java.lang.String getShip_pos() {
		return SHIP_POS;
	}

	private java.lang.String SUBVENDOR_NAME;

 	public void setSubvendor_name(java.lang.String SUBVENDOR_NAME) {
		this.SUBVENDOR_NAME = SUBVENDOR_NAME;
	}

	public java.lang.String getSubvendor_name() {
		return SUBVENDOR_NAME;
	}

	private java.lang.String DELIVERY_DATE;

 	public void setDelivery_date(java.lang.String DELIVERY_DATE) {
		this.DELIVERY_DATE = DELIVERY_DATE;
	}

	public java.lang.String getDelivery_date() {
		return DELIVERY_DATE;
	}

	private java.lang.String IDENT_DESC;

 	public void setIdent_desc(java.lang.String IDENT_DESC) {
		this.IDENT_DESC = IDENT_DESC;
	}

	public java.lang.String getIdent_desc() {
		return IDENT_DESC;
	}

	private java.lang.Integer ID_INSPECTION_LEVEL;

 	public void setId_inspection_level(java.lang.Integer ID_INSPECTION_LEVEL) {
		this.ID_INSPECTION_LEVEL = ID_INSPECTION_LEVEL;
	}

	public java.lang.Integer getId_inspection_level() {
		return ID_INSPECTION_LEVEL;
	}

	private java.lang.String DELIVERY_PLACE;

 	public void setDelivery_place(java.lang.String DELIVERY_PLACE) {
		this.DELIVERY_PLACE = DELIVERY_PLACE;
	}

	public java.lang.String getDelivery_place() {
		return DELIVERY_PLACE;
	}

	private java.lang.String INSPECTION_LEVEL;

 	public void setInspection_level(java.lang.String INSPECTION_LEVEL) {
		this.INSPECTION_LEVEL = INSPECTION_LEVEL;
	}

	public java.lang.String getInspection_level() {
		return INSPECTION_LEVEL;
	}

	private java.lang.String SECTION;

 	public void setSection(java.lang.String SECTION) {
		this.SECTION = SECTION;
	}

	public java.lang.String getSection() {
		return SECTION;
	}

	private java.lang.Integer ID_LOCATION;

 	public void setId_location(java.lang.Integer ID_LOCATION) {
		this.ID_LOCATION = ID_LOCATION;
	}

	public java.lang.Integer getId_location() {
		return ID_LOCATION;
	}

	private java.lang.String INSPECTION_LEVEL_PREV;

 	public void setInspection_level_prev(java.lang.String INSPECTION_LEVEL_PREV) {
		this.INSPECTION_LEVEL_PREV = INSPECTION_LEVEL_PREV;
	}

	public java.lang.String getInspection_level_prev() {
		return INSPECTION_LEVEL_PREV;
	}

	private java.lang.Integer ID_EXPEDITION_LEVEL_PREV;

 	public void setId_expedition_level_prev(java.lang.Integer ID_EXPEDITION_LEVEL_PREV) {
		this.ID_EXPEDITION_LEVEL_PREV = ID_EXPEDITION_LEVEL_PREV;
	}

	public java.lang.Integer getId_expedition_level_prev() {
		return ID_EXPEDITION_LEVEL_PREV;
	}

	private java.lang.String TAG;

 	public void setTag(java.lang.String TAG) {
		this.TAG = TAG;
	}

	public java.lang.String getTag() {
		return TAG;
	}

	private java.lang.String EXPEDITION_LEVEL_PREV;

 	public void setExpedition_level_prev(java.lang.String EXPEDITION_LEVEL_PREV) {
		this.EXPEDITION_LEVEL_PREV = EXPEDITION_LEVEL_PREV;
	}

	public java.lang.String getExpedition_level_prev() {
		return EXPEDITION_LEVEL_PREV;
	}

	private java.lang.String POS_SUB;

 	public void setPos_sub(java.lang.String POS_SUB) {
		this.POS_SUB = POS_SUB;
	}

	public java.lang.String getPos_sub() {
		return POS_SUB;
	}

}